# Generated by Django 2.1.5 on 2019-03-08 12:44

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20190228_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='image',
        ),
        migrations.AddField(
            model_name='job',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='display_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='job',
            name='portfolio_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='job',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
