# Generated by Django 2.1.5 on 2019-04-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20190308_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(default='keyword-wrapper'),
            preserve_default=False,
        ),
    ]
