# Generated by Django 2.1.5 on 2019-08-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='url',
            new_name='link_to_project',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='slug',
            new_name='url_slug',
        ),
        migrations.AlterField(
            model_name='job',
            name='portfolio_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
