# Generated by Django 2.1.5 on 2019-08-07 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20190807_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='date_created',
            field=models.DateField(default=datetime.date(2019, 8, 7)),
        ),
    ]
