# Generated by Django 2.1.5 on 2019-10-06 21:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20191006_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobimage',
            name='type',
            field=models.CharField(choices=[('TN', 'Thumbnail'), ('DS', 'Display')], default='DS', max_length=2),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2019, 10, 6, 21, 4, 0, 48073, tzinfo=utc)),
        ),
    ]
