# Generated by Django 2.1.5 on 2019-10-06 21:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_auto_20191006_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2019, 10, 6, 21, 39, 24, 999984, tzinfo=utc)),
        ),
    ]
