# Generated by Django 2.1.5 on 2019-10-06 21:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_auto_20191006_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2019, 10, 6, 21, 46, 37, 132834, tzinfo=utc)),
        ),
    ]
