# Generated by Django 2.1.5 on 2019-10-07 20:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_auto_20191006_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_created',
            field=models.DateField(default=datetime.datetime(2019, 10, 7, 20, 44, 0, 167428, tzinfo=utc)),
        ),
    ]
