# Generated by Django 2.1.5 on 2019-10-07 20:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_auto_20191007_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobimage',
            name='order',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
