# Generated by Django 2.1.5 on 2019-10-07 21:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_job_technologies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='technologies',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None),
        ),
    ]
