# Generated by Django 2.1.5 on 2019-10-15 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_auto_20191007_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='display_image',
        ),
        migrations.RemoveField(
            model_name='job',
            name='portfolio_image',
        ),
    ]
